### ISSUE TITLE
Rotations and logs are orphaned if herds or paddocks are removed

### ISSUE THREAD

**Issue by mstenta** [farmOS/farm_grazing#12]
If a herd or paddock is removed from the plan, after rotations have been created that reference them, those rotations are orphaned in the database, along with any logs that were maintained alongside them.

**Comment by mstenta** [comment]
I have some `@todo`s in place already in my local code for this - so I'll assign this to myself. It should be pretty easy.

**Comment by woodbri** [comment]
I'm not sure we want to delete these. I'm thinking about the situation where you want to look back a plan at  an earlier point in time. For example we want to look at what was originally planned and see how and why the plan changed over its lifetime. We might not be able to do that yet, but I think it is a goal we might want to discuss and spec out the effort.

**Comment by mstenta** [comment]
Agreed it will be nice to explore that feature. We do need to delete these in the meantime, though. It is currently creating a bunch of logs that are cluttering the todo list. We will need to enable revisions on plans and store revision IDs along with the rotations in order to keep them moving forward, but for now they are just orphaned and we don't have any information about when/why they were.

**Comment by mstenta** [comment]
Fixed: https://github.com/mstenta/farm_grazing/commit/f160b52cffbbfe5f00cedf677513ee5a6f1f6d92
