### ISSUE TITLE
Herds / Manage form shows incorrect animal departure and arrival dates

### ISSUE THREAD

**Issue by mstenta** [farmOS/farm_grazing#15]
If an animal has a planned arrival or departure date that is outside the date range of the plan itself, then the Herds / Manage form displays the plan's start/end dates instead of the animal's arrival/departure date.

This is because the functions for loading and validating herd data are intertwined in such a way that it "corrects" the dates to be within the plan date range, so that the calculations that happen elsewhere in the code are not thrown off by arrival/departures that are years ahead/behind the plan.

This is necessary for calculations, but it introduces a potential bug with the animal dates displayed in the form. For one, it's confusing to see dates that don't match the animal's actual arrival/departure properties. But also, if you try to change one (or both) of them via the herds form, then it will overwrite the actual values stored on the animal, which could lead to potential data loss that won't be clear to the user unless they look at the animal record itself.

The functions for loading and validating herd data should be separated, so that the form can show the actual values, but all calculations are done with the "corrected" values.

**Comment by mstenta** [comment]
I've started investigating this already, so I'm assigning this to myself.

**Comment by mstenta** [comment]
>  if you try to change one (or both) of them via the herds form, then it will overwrite the actual values stored on the animal

This is mitigated by the fact that the form submit function will ONLY change those values on the animal record if it detects that a change was made in the form itself to one of those values (it compares the form fields' #default_value to the actual submitted value - and if they are the same, then it doesn't do anything). So it's only an issue if the user actually does make a change to one of those values.

**Comment by woodbri** [comment]
ok, this is weird, we load the data in farm_grazing_validate_herd() in farm_grazing.utils.inc and and directly via ``$arrival = farm_asset_property_get($asset_id, 'farm_grazing_planned_arrival');``, but I can't find where we are actually using that data other than in the farm_grazing.herds.rotations.plot.inc which is only called via img tags in farm_grazing.herds.rotations.inc

So it might be that the logic to clip the date range just needs to get moved into the plot code.

**Comment by mstenta** [comment]
Ah ok - could be.

Is it used when generating the start and end dates of the rotation itself? Or the duration? Or can a rotation stretch beyond the end date of a plan (I suppose it should be able to)?

**Comment by woodbri** [comment]
rotations are all based on start date plus duration. and in theroy we can let the duration extend off the end of the plan. The duration just represents the amount of forage that we expect is available for the herd in the paddock.

**Comment by mstenta** [comment]
Yea I was just wondering if the plan cutoff dates get factored in at all in the logic that's generating the duration - but that's sort of a dumb question because I just refactored that code, so I already know the answer. They do not. So yea, maybe it's only being used in the plotting - in which case it would be easy to only perform the arrival/departure cropping in the plotting code.

**Comment by mstenta** [comment]
@woodbri fixed this - thanks!
