### ISSUE TITLE
Update rotations when a log date changes

### ISSUE THREAD

**Issue by mstenta** [farmOS/farm_grazing#16]
I just realized I forgot to finish this piece... there is currently a `@todo` in the module which needs to be replaced with real code.

If a log's date changes (for a log that is associated with a rotation), the module needs to automatically update the dates of all rotations (and their logs) that come after that one in the plan.

Here is the `@todo`: https://github.com/mstenta/farm_grazing/blob/7.x-1.x/farm_grazing.module#L793

**Comment by mstenta** [comment]
Assigning this to myself.

**Comment by mstenta** [comment]
Here are the steps I think we need to code up to finish this (where the `@todo` is currently in the `farm_grazing_plan_log_update($log)` function):

- Load information about the rotation this log is tied to.
- Load up all rotations of the same herd in the plan.
- Update the duration of the previous rotation.
- Update the start date of this rotation.
- Recalculate the start dates and durations of all rotations after it.
- Update the timestamps of all linked logs.

**Comment by woodbri** [comment]
I've been thinking about the whole planning process, and it seems to me that it exists in two separate states. The first state is the planning state where you are building your plan. During this phase you might make changes to see how things look experiment with adding or removing paddocks or animals from the herd, etc. Think of this as your local branch in git before you commit.
The second state occurs when you commit the plan and you are making changes based on actuals.

The first part could add a lot of noise to the logs if every changes is kept, but all people really need is those that they commit. If we change the page behavior to be ajax based then the save button becomes the commit feature. We could keep the local branch (uncommitted) in the rotations table and only push it to the logs when it is committed.

I think building a system that behaves like a simple git makes a lot of sense. "Branches" could be named, archived, activated, changed and re-committed. This would make it easier to compare various branches or planned versus actual.

**Comment by mstenta** [comment]
This is interesting - I like it! Perhaps we can spin up a new issue to discuss it in more detail.

I also have been thinking that we might want to make a separate step in the process for "Creating the logs" associated with rotations. So, like you said, you could play around with plans, and then "Commit" them to a set of logs that you're working with moving forward.

**Comment by mstenta** [comment]
Ok, I've got this working properly now, I think.

It uses the new recalculation function that I wrote in #20, so it depends on that branch.

I created a new branch called "issue16" that branches off of the merged changes from #20.

**Comment by mstenta** [comment]
Done!
