### ISSUE TITLE
Follow Drupal function naming convention

### ISSUE THREAD

**Issue by mstenta** [farmOS/farm_grazing#19]
This is low priority, but if we have a chance we should do it...

According to the "Naming conventions" section of the Drupal coding standards:

> Functions should be named using lowercase, and words should be separated with an underscore. Functions should in addition have the grouping/module name as a prefix, to avoid name collisions between modules.

https://www.drupal.org/docs/develop/standards/coding-standards#naming

There are a number of functions in the module (mostly in farm_grazing.utils.inc) that should be renamed to meet these standards. The two main things to fix are:

1. Namespacing - function names should all begin with `farm_grazing_` to prevent potential overlaps with functions provided by other modules. For example: use `farm_grazing_get_paddocks()` instead of `get_paddocks()`.

2. Camel case - function names shouldn't use camel case (only methods inside classes should). For example: use `farm_grazing_get_paddocks()` instead of `farmGrazingGetPaddocks()`.

**Comment by woodbri** [comment]
I'll clean this up in a branch when I have a chance. Assigning to myself.

**Comment by mstenta** [comment]
Cool! Obviously no rush... low priority. Just adding todo items as they pop up so we have it all documented. :-)

**Comment by mstenta** [comment]
@woodbri made a branch that did this - and it is now merged.
