### ISSUE TITLE
Show all plan starting/ending paddocks in History tab

### ISSUE THREAD

**Issue by mstenta** [farmOS/farm_grazing#23]
In the Herds > History tab, it would be nice to show a brief report of where herds started/ended in other plans.

The use-case is: if you are starting a new plan, you might not want to start your herd in the same paddock that you ended them in in the last plan.

So by showing a quick summary of other plans (including both growing and non-growing), you would have all the info you need to make that decision quickly, without having to click around to look at the other plans.

**Comment by woodbri** [comment]
OK, so this would be generating a new table with columns like:

- Plan Name
- Start date
- End date
- Start paddock
- End paddock

order by Start date descending and limited by the number of years selected for the history.

Can you give me a quick refresher on how to fetch that info?

**Comment by mstenta** [comment]
Yea basically, but I think the info could just be fetched from existing tables - no need for a new one.

The plan name will be in the {farm_plan} table, and the start and end dates will be in {field_data_field_farm_date_range} (linked to the {farm_plan} table by "entity_type" = "farm_plan" and "entity_id" = the plan ID).

So those could be fetched with a single query.

The start and end paddocks would be in the {farm_grazing_rotations}.  Maybe they could be fetched in the same query as well.  But if that's tricky then a second query to look up the MIN() and MAX() rotation weight/order would do it I think.

One consideration: a plan will have a separate start/end paddock for EACH herd - so it may have more than one per plan.

**Comment by mstenta** [comment]
This will get you the plan ID, name, and start and end dates:

```
SELECT *
FROM farm_plan p
LEFT JOIN field_data_field_farm_date_range d ON d.entity_type = 'farm_plan' AND d.entity_id = p.id;
```

**Comment by woodbri** [comment]
Started this and pushed WIP to branch issue23

**Comment by mstenta** [comment]
Merged!
