### ISSUE TITLE
SAU column wrong in herd details (with head count)

### ISSUE THREAD

**Issue by mstenta** [farmOS/farm_grazing#25]
In Herds > Manage, in the herd details lists (where each animal record is shown), the SAU column is not being multiplied by the animal's head count.

So for example, if you have an animal record with a head count of 100, and an average weight of 750 lbs, the SAU is listed as "0.75".  The actual SAUs in that case would be 75.

Notably, in the "Summary of Herds in Plan" at the top of the page, the correct value is shown.

So I think the math is correct in the Summary section, but not in the Herd Details section.

**Comment by woodbri** [comment]
Its an issue of "Total SAU" vs "Average SAU" Notice the column beside it has Weight which is the Average Weight not the Total weight. So it can be changed, but maybe better labeling is all that is needed.  And on the column to the right of SAU we have Daily Intake (not clear if that is Total or Average?) I'm guessing it is Total based on the numbers.

**Comment by mstenta** [comment]
Yea that was my thought too. I think it just needs to multiply by the head count in the herd details, like it's already doing in the summary at the top (I think). And also maybe adding some label to indicate that it's an average weight when the headcount is >1.

**Comment by mstenta** [comment]
Oh I see what you meant now... I think the column should be re-labelled "Total SAU" and should multiply by the head count.  And the "Weight" column should be re-labelled to "Average Weight".

My reasoning is that because "Weight" is editable, we don't want that to be "Total Weight" - but for SAU it's more useful to see what the total SAU of the record is than it is to know the average SAU. At least that's what I would think.

**Comment by mstenta** [comment]
Merged! Thanks @woodbri ! This looks great.

Quick description in case anyone comes across this later, this is a summary of the changes:

1. Change "Weight" column to "Weight (Average)" - to make it clear that in animal records that have a head count greater than 1, the weight represents average animal weight.
2. Add a new column "Total weight" that multiplies head count by average weight - to make that even more clear.
3. Modify the SAU calculation so that it also multiplies by head count - so now the Total Weight, SAU, and Daily Intake all show totals, not averages.
