### ISSUE TITLE
It's possible to mark rotations as "done" out of order

### ISSUE THREAD

**Issue by mstenta** [farmOS/farm_grazing#28]
Rotations are linked to movement logs (which are autogenerated). And marking those logs as "done" locks the rotation in the plan so it can't be changed or rearranged. This works well for the most part. It is possible, however, to mark logs "done" in a different order, and that may cause unexpected things to happen.

For instance, if you have 5 rotations. You could mark rotation 2 as done before you mark rotation 1. Then, in the rotations form, rotations 1, 3, 4, and 5 are moveable, but rotation 2 is not.  I haven't tested this, but it may mean it's possible to end up with some weird results - if you were to try to drag those items around the "done" one in the middle.

**Comment by mstenta** [comment]
I had a idea for a general way to solve this (which would also be a nice feature to have elsewhere in farmOS): dependent logs.

Imagine if each log could optionally "depend" on another log. So you wouldn't be able to mark one log as done until it's dependencies were also marked as done.

Then, using that system, the grazing module could just make sure that all the rotations form a chain of log dependency. So you couldn't mark log 2 done until you marked log 1 done.

Each time the rotations were rearranged, you would also have to reassign the dependency chain, but that could happen in the same recalculation function that is recalculating the dates.

**Comment by mstenta** [comment]
I created a new feature request in the farmOS issue queue for dependent logs: https://www.drupal.org/project/farm/issues/2940414

Once that lands, we can continue this feature request by leveraging it with rotations.

**Comment by woodbri** [comment]
So in your example, marking 2 done before 1 seems like an implicit reordering of the paddocks. So this might be easier solved by not allowing a paddock to marked as done unless its predecessor is done. We should generate an alert like: "Marking paddocks as done out of order. Check that you really want to do this and reorder the paddocks if needed." I think keeping it simple is the best approach.

**Comment by mstenta** [comment]
Yes exactly! And I think the "dependent logs" feature is a good way to solve that (and may also provide usefulness elsewhere).  It can start as a simple invisible property of logs that just references another log ID (or perhaps multiple).  Combined with some logic when a log is being saved (and marked as done) to prevent it and show the warning.

**Comment by mstenta** [comment]
I took a more direct approach to solve this directly in the farm_grazing module, rather than creating a more generalized "dependent logs" feature in farmOS itself. We can move this logic out of farm_grazing and into farmOS core if/when it needs to be generalized for other modules to take advantage of.  But for now, the grazing module already keeps track of the order of rotations, so it can enforce the order in which logs are marked "done" all by itself.

https://github.com/farmOS/farm_grazing/commit/9b732f9745a454dc17c34438b2bad022c03cb5e4
