### ISSUE TITLE
Render rotation calendar rows with HTML+CSS

### ISSUE THREAD

**Issue by mstenta** [farmOS/farm_grazing#30]
Currently we are rendering the rotation calendars (in /farm/plan/%/herds/rotations) as SVG images.

As we build the "considerations" features (https://github.com/mstenta/farm_grazing/issues/22), more colored bars will be added to the rotation calendar images.

It won't be easily visible what each represents.  Ideally you could click on one and it would show a tooltip that describes what it is.  However, when they are all rendered into a single SVG image, this is not possible.

So instead, let's explore the possibility of rendering this in pure HTML and CSS. Each consideration can be a separate DIV with `style` and/or `class` tags to size and color it appropriately, and to attach a tooltip to (Bootstrap provides a tooltip feature we can use).

We may want to examine how Bootstrap's grid system classes work, because it may provide a good basis for developing our own CSS classes for this purpose: https://getbootstrap.com/docs/3.3/css/#grid

**Comment by mstenta** [comment]
We could also put the "Date range" column information into the tooltip, thus freeing up more space for visual calendar column.

**Comment by mstenta** [comment]
> However, when they are all rendered into a single SVG image, this is not possible.

Steve found some examples of doing something like this directly in SVGs:

https://codepen.io/bastienff/pen/lervL

https://css-tricks.com/click-svg-to-focus/

So maybe that is an option, after all!  It would certainly be simpler than HTML+CSS.

We'll have to see what the browser support is, if it's widely available.

**Comment by mstenta** [comment]
Or.... https://github.com/mstenta/farm_grazing/issues/36

**Comment by woodbri** [comment]
I looked into implementing the first link above, but it does not work with SVG in iIMG tags, so we would need to move the SVG code for the image directly into the TD tag and then try again.

**Comment by mstenta** [comment]
Ah ok I didn't know that about IMG vs direct SVG.  Well, there's an easy solution: we can create a theme function for the plotting.  Basically, instead of it being a page callback (which the <img src="..." tag points to), we would call something like $output = theme('rotations-plot', ...) directly in the code for building the rotations table.  As long as your plot code is just outputting SVG tags, that should work.  We'll also remove the lines from the current plot function that are setting header information, etc.  That's actually a very elegant way to do this, I like it!

**Comment by woodbri** [comment]
OK, we now have SVG directly in the table TD cells and these are working with CSS and a little JS to provide tooltips when hover over the individual rectangles in the SVG.  This will be part of the next sprint we release, so I'm closing this.
