### ISSUE TITLE
D3.js for rotation visualizations?

### ISSUE THREAD

**Issue by mstenta** [farmOS/farm_grazing#36]
I've been playing around a bit with D3.js (https://d3js.org/) and it's gotten my gears turning.

It might be worth experimenting with it for plotting the rotations. It could potentially replace the entire table in the rotations form.

@woodbri pointed out that it should be done in a way that ensures you can still use the form without Javascript (graceful degradation) - so perhaps we could add it as an optional add-on.

**Comment by mstenta** [comment]
Some examples that could inspire us:

https://bl.ocks.org/mbostock/4061961
https://bl.ocks.org/mbostock/4063318
http://square.github.io/cubism/

**Comment by woodbri** [comment]
I think this can be closed as wont fix. As we discussed, this puts a heavy dependency on JS and we are accomplishing most of what we want with SVG, HTML, and CSS. Also, I think we can generate a whole grazing chart just using PHP and SVG. See issue #38

**Comment by mstenta** [comment]
Fine with me - this is something we can explore in the distant future perhaps. :-)
