### ISSUE TITLE
Add a "Herds > Projections" tab for entering projected weight gain and head counts over time for the plan

### ISSUE THREAD

**Issue by woodbri** [farmOS/farm_grazing#48]
Add a "Herds > Projections" tab for entering projected weight gain over time for the plan, which can then be displayed in the grazing chart.  This would be separate from the existing weight measurement logs that you're using for "actual" weight, and would be primarily for projection planning purposes.

**Comment by mstenta** [comment]
Potential database table structure:

{farm_grazing_herd_projection}
- plan_id
- herd_id
- date
- head_count
- avg_weight

**Comment by mstenta** [comment]
Let's call the tab "Projections" instead of "Weight" so that it's more general (it also includes Head Count).

**Comment by woodbri** [comment]
So I'm thinking of creating a page something like with months of the plan:

## Herd: Herd 1

xxxx | Jan | Feb | Mar | Apr | May | ...
---- | --- | --- | --- | --- | --- | ---
Avg. Weight | ... | ... | ... | ... | ... | ...
Initial Head Cnt| ... | ... | ... | ... | ... | ...
Births | ... | ... | ... | ... | ... | ...
Harvests | ... | ... | ... | ... | ... | ...
Head Count | ... | ... | ... | ... | ... | ...

## [Save]

Optionally add a helper field like:
% Weight gain / month [  10] (Update)

That would increase the weight entered on the first field by 10% (in this example) each month. This would not be saved it would only be used to compute and populate fields in each month and users could then edit those values.

Initial Head count would be populated based on herd arrival and departure data. Then births would be added to that and harvests subtracted and the Head Count would computed when rendered. Initial Head count and Head Count would not be editable.

For multiple herds additional tables would be presented.

**Comment by woodbri** [comment]
## Implementation Details:

- data will be displayed in table from a db table
- table will be a form that is submitted
- user can edit data in the table and be saved
- data will get validated
- db will get updated with data
- no versioning of data will get tracked, if projections change over time no attempt will be made to remember these changes.
- grazing chart will be updated to display this data

**Comment by woodbri** [comment]
Added form and DB for capturing this data to branch sprint5, still need to update calculations to incorporate this new data.

**Comment by woodbri** [comment]
Completed in Sprint 5
