### ISSUE TITLE
Add a form that gives options for generating the grazing chart

### ISSUE THREAD

**Issue by woodbri** [farmOS/farm_grazing#52]
Add a form that gives options for generating the grazing chart (currently you need to know the exact link in order to view it, so this would just create a UI for that).

https://github.com/mstenta/farm_grazing_chart (private)

**Comment by woodbri** [comment]
Add Reports tab before Settings tab, it will be empty initially, unless you activate the charting module which will add to the Reporting index list. Move the History report into the Reports Tab.

**Comment by woodbri** [comment]
## Implementation details:

- create a new tab "Reports" to replace the current "History" tab
- In the reports tab, display an index of reports
- Add the current "History" tab to the index list
- update Grazing chart module to add an index entry when it is installed

## Concerns
I'm a little worried about burying the "History" tab inside the "Reports" tab as it is important to the planning workflow. Also not sure the "Reports" tab should be in "Herds" as we can have "Reports" on paddocks and on the plan in general.

I'm thinking that we need a top level "Reports" tab that all reports are indexed into, and then Herds -> History is just a short-cut to that plan. and we add a Herds -> Projections tab which is also a short-cut to that report.

**Comment by mstenta** [comment]
We could keep this task isolated for now and not worry about reorganizing tabs or creating a new "Reports" tab yet... And then create a separate task for that specifically so we can think through the considerations and best layout thoroughly.

What if we just add a new "Chart" tab after "Rotations" for now, and that's where the form for generating the grazing chart PDF goes.  This would be a single hook_menu() item in the farm_grazing_chart.module, along with a simple form that exposes the chart rendering options.

**Comment by woodbri** [comment]
Closing this with commit To git@github.com:mstenta/farm_grazing_chart.git
   a47ce92..3745a73  sprint5 -> sprint5
