### ISSUE TITLE
Create a simple "Feed" asset type and "Purchase" log

### ISSUE THREAD

**Issue by woodbri** [farmOS/farm_grazing#54]
Create a simple "Feed" asset type and "Purchase" log type that can be used to record purchases of assets, and store documents alongside them.  Jess specifically asked about storing paperwork for organic feed that was purchased recently.

from #39 

supplement or feed - type and amount by date (we might have this but it needs to be standardized so I know what I'm reporting in the grazing chart - review with Kelly)

**Comment by mstenta** [comment]
> supplement or feed - type and amount by date (we might have this but it needs to be standardized so I know what I'm reporting in the grazing chart - review with Kelly)

That is a separate task from this one. This is simply to add a "Feed" asset type and a "Purchase" log type for recording when feed was purchased.  Recording of animal feedings will take place with an input log (and technically this can already be done - but I agree we will need to settle on a standardized method for showing that in the grazing chart.  But that's a separate task from this one.)

**Comment by mstenta** [comment]
Purchase log is done: https://www.drupal.org/project/farm/issues/2962075

**Comment by mstenta** [comment]
Closing this - the Feed asset type is not immediately needed (talked this through with Kelly a few weeks ago) - it was mainly the Purchase logs that were for organic certification requirements. I'd rather hold off on Feed management until the more general inventory handling features are in place. Then a Feed or Materials asset type will be easy and fully-functional.
