### ISSUE TITLE
Better handling of recovery periods for rotations

### ISSUE THREAD

**Issue by woodbri** [farmOS/farm_grazing#7]
Recovery periods should probably be changed to logs so that they are presented correctly in the rotations table.

For example in the non-growing season if you are doing 2 rotations through the paddocks, the first rotation's recovery period should show up on the second rotations line. Also if you create a new plan, any of the recovery periods from prior plan grazing should show up on the current plan if they intersect time wise with that plan.

**Comment by mstenta** [comment]
Can this information be loaded from the {farm_grazing_rotations} table?

> if you are doing 2 rotations through the paddocks, the first rotation's recovery period should show up on the second rotations line

This could be accomplished by looking at the other rotations in the plan.

> if you create a new plan, any of the recovery periods from prior plan grazing should show up on the current plan if they intersect time wise with that plan

Agree this would be a nice feature.  Maybe it could be optional - ie: "Show intersections with rotations from other plans" that you could toggle on/off - or maybe even allow you to select which plans you want to show.

I could envision a farm setting up multiple plans to try out different ideas - but not necessarily using all of them.  So having the ability to select which plans to show in the rotations as overlapping lines would be useful for that.

**Comment by woodbri** [comment]
I don't think it should be optional. Consider the case where paddock A was grazed at the end of some other plan, and now you are make a new plan. You would want to know when paddock A was last grazed (ie: by its recovery period) so you would not graze it again until it had recovered.

**Comment by mstenta** [comment]
The reason I suggested that it be configurable/optional is described in my last paragraph:

> I could envision a farm setting up multiple plans to try out different ideas - but not necessarily using all of them. So having the ability to select which plans to show in the rotations as overlapping lines would be useful for that.

Imagine I set up three plans for 2018 - to think through different possible variations.  I wouldn't want them to be affected by each other. But I would want them to be affected by previous plans or overlapping plans.

I suppose you could simply have it only include information from "active" plans. Then you could still create the three plans for experimenting, but mark them as "not active".

**Comment by woodbri** [comment]
I would be a nice feature to hover over a feature in the rotation planning table and to show a tooltip that described there that feature came from. For example hovering over a recovery period would tell you what plan that was grazed in. Also we could hide features that are older than some number of configurable days to filter out old noise. maybe this should be mentioned in #1

**Comment by mstenta** [comment]
I think we'll be able to handle this with #22 - I'm going to close this, but link to it from that issue.
