### ISSUE TITLE
Change planned arrival/departure storage to unix timestamps

### ISSUE THREAD

**Issue by woodbri** [farmOS/farm_grazing#9]
"planned arrival/departure" date need to be in the format YYYY-MM-DD in the farm_asset_property table. These should get change to timestamps. Check for other cases like this in the code.

The one exception is exclusions that need the dates split into 3 fields for YYYY, MM, DD where YYYY may be NULL for an annually recurring event associated to the paddock.

**Comment by mstenta** [comment]
I started working on this - should be pretty simple.

**Comment by mstenta** [comment]
I updated the title of this to be specifically about the planned arrival/departure dates.

Regarding the point about exclusions:

> The one exception is exclusions that need the dates split into 3 fields for YYYY, MM, DD where YYYY may be NULL for an annually recurring event associated to the paddock.

Exclusion dates are currently stored as timestamps, but when we make exclusions into a general type of management concern, we can change that (or use the date range field type provided by Drupal): #22

**Comment by mstenta** [comment]
I pushed a commit that makes this change. Note that it adds an update hook, so you need to run update.php on the site after updating.

https://github.com/mstenta/farm_grazing/commit/06919de9315062d559d91b4a2914fae32f95b674

It basically just changes the code that loads and saves the dates.  But it still converts them to 'Y-m-d' format for use in the other areas of code.
